# -*- coding: utf-8 -*-
#
# Form implementation generated from reading ui file 'temp_1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def __init__(self):
        self.stdo = 1
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1124, 750)
        MainWindow.setMinimumSize(QtCore.QSize(1124, 750))
        MainWindow.setMaximumSize(QtCore.QSize(1124, 750))
        font = QtGui.QFont()
        font.setFamily("华文彩云")
        font.setPointSize(16)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(30, 440, 731, 251))#设置layout大小与位置
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.fileselect = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.fileselect.setContentsMargins(0, 0, 0, 0)
        self.fileselect.setObjectName("fileselect")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.line_Directory = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.line_Directory.setObjectName("line_Directory")
        self.horizontalLayout_4.addWidget(self.line_Directory)
        self.button_Browse = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        self.button_Browse.setFont(font)
        self.button_Browse.setObjectName("button_Browse")
        self.horizontalLayout_4.addWidget(self.button_Browse)
        self.fileselect.addLayout(self.horizontalLayout_4)
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setGridStyle(QtCore.Qt.DashLine)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setObjectName("tableWidget")
        self.fileselect.addWidget(self.tableWidget)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(790, 470, 301, 221))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 30, 731, 381))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.mainwindow = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.mainwindow.setContentsMargins(0, 0, 0, 0)
        self.mainwindow.setObjectName("mainwindow")
        self.mpl = MplWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl.sizePolicy().hasHeightForWidth())
        self.mpl.setSizePolicy(sizePolicy)
        self.mpl.setObjectName("mpl")
        self.mainwindow.addWidget(self.mpl)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(790, 40, 301, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(20, 30, 211, 80))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.buttonlay = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.buttonlay.setContentsMargins(0, 0, 0, 0)
        self.buttonlay.setObjectName("buttonlay")
        self.folderbutton = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.folderbutton.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.folderbutton.setFont(font)
        self.folderbutton.setMouseTracking(True)
        self.folderbutton.setCheckable(True)#封印住选项!!!
        self.folderbutton.setAutoExclusive(True)#设置自动排他性!!!
        self.folderbutton.setChecked(False)
        self.folderbutton.setObjectName("folderbutton")
        self.buttonlay.addWidget(self.folderbutton)
        self.directlybutton = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.directlybutton.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.directlybutton.setFont(font)
        self.directlybutton.setMouseTracking(True)
        self.directlybutton.setChecked(True)
        self.directlybutton.setObjectName("directlybutton")
        self.buttonlay.addWidget(self.directlybutton)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(790, 390, 301, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.selectlay = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.selectlay.setContentsMargins(0, 0, 0, 0)
        self.selectlay.setObjectName("selectlay")
        self.selectButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.selectButton.setFont(font)
        self.selectButton.setObjectName("selectButton")
        self.selectlay.addWidget(self.selectButton)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.selectlay.addItem(spacerItem)
        self.stopButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.stopButton.setFont(font)
        self.stopButton.setObjectName("stopButton")
        self.selectlay.addWidget(self.stopButton)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(790, 180, 301, 200))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.setting = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.setting.setContentsMargins(0, 0, 0, 0)
        self.setting.setObjectName("setting")
        # self.setting_1 = QtWidgets.QHBoxLayout()
        # self.setting_1.setObjectName("setting_1")
        # self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        # self.label.setFont(font)
        # self.label.setObjectName("label")
        # self.setting_1.addWidget(self.label)
        # self.thresholdSlider = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.thresholdSlider.sizePolicy().hasHeightForWidth())
        # self.thresholdSlider.setSizePolicy(sizePolicy)
        # self.thresholdSlider.setMaximum(30)
        # self.thresholdSlider.setSliderPosition(15)
        # self.thresholdSlider.setOrientation(QtCore.Qt.Horizontal)
        # self.thresholdSlider.setObjectName("thresholdSlider")
        # self.setting_1.addWidget(self.thresholdSlider)
        # self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        # self.lineEdit_2.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        # self.lineEdit_2.setFont(font)
        # self.lineEdit_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        # self.lineEdit_2.setObjectName("lineEdit_2")
        # self.setting_1.addWidget(self.lineEdit_2)
        # self.setting.addLayout(self.setting_1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.setting.addItem(spacerItem1)
        self.setting_2 = QtWidgets.QHBoxLayout()
        self.setting_2.setObjectName("setting_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.setting_2.addWidget(self.label_2)
        self.peakthresholdbox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        self.peakthresholdbox.setFont(font)
        self.peakthresholdbox.setDecimals(2)
        self.peakthresholdbox.setMinimum(0.5)
        self.peakthresholdbox.setMaximum(2.0)
        self.peakthresholdbox.setSingleStep(0.01)
        self.peakthresholdbox.setProperty("value", 1.25)
        self.peakthresholdbox.setObjectName("peakthresholdbox")
        self.setting_2.addWidget(self.peakthresholdbox)
        self.setting.addLayout(self.setting_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.setting.addItem(spacerItem2)
        self.setting_3 = QtWidgets.QHBoxLayout()
        self.setting_3.setObjectName("setting_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.setting_3.addWidget(self.label_3)
        self.triggerbox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        self.triggerbox.setFont(font)
        self.triggerbox.setDecimals(1)
        self.triggerbox.setMinimum(-2.0)
        self.triggerbox.setMaximum(0.0)
        self.triggerbox.setSingleStep(0.1)
        self.triggerbox.setProperty("value", -1.0)
        self.triggerbox.setObjectName("triggerbox")
        self.setting_3.addWidget(self.triggerbox)
        self.setting.addLayout(self.setting_3)
        spacerItem3 = QtWidgets.QSpacerItem(294, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.setting.addItem(spacerItem3)
        self.analy_1 = QtWidgets.QHBoxLayout()
        self.analy_1.setObjectName("analy_1")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.analy_1.addWidget(self.label_5)
        self.peakthresholdbox_2 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        self.peakthresholdbox_2.setFont(font)
        self.peakthresholdbox_2.setDecimals(2)
        self.peakthresholdbox_2.setMinimum(0.5)
        self.peakthresholdbox_2.setMaximum(2.0)
        self.peakthresholdbox_2.setSingleStep(0.01)
        self.peakthresholdbox_2.setProperty("value", 1.25)
        self.peakthresholdbox_2.setObjectName("peakthresholdbox_2")
        self.analy_1.addWidget(self.peakthresholdbox_2)
        self.setting.addLayout(self.analy_1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.setting.addItem(spacerItem4)
        self.analy_2 = QtWidgets.QHBoxLayout()
        self.analy_2.setObjectName("analy_2")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.analy_2.addWidget(self.label_6)
        self.triggerbox_2 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        self.triggerbox_2.setFont(font)
        self.triggerbox_2.setDecimals(1)
        self.triggerbox_2.setMinimum(-2.0)
        self.triggerbox_2.setMaximum(0.0)
        self.triggerbox_2.setSingleStep(0.1)
        self.triggerbox_2.setProperty("value", -1.0)
        self.triggerbox_2.setObjectName("triggerbox_2")
        self.analy_2.addWidget(self.triggerbox_2)
        self.setting.addLayout(self.analy_2)
        MainWindow.setCentralWidget(self.centralwidget)#对栏目进行定义
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1119, 28))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        #self.menuFile_open = QtWidgets.QMenu(self.menuFile)
        #self.menuFile_open.setObjectName("menuFile_open")
        self.menuFile_exit = QtWidgets.QMenu(self.menuFile)
        self.menuFile_exit.setObjectName("menuFile_exit")
        #self.actionopen_file = QtWidgets.QAction(MainWindow)
        #self.actionopen_file.setObjectName("actionopen_file")
        #self.actionopen_file.setStatusTip('Open file——打开文件！')
        #self.actionopen_folder = QtWidgets.QAction(MainWindow)
        #self.actionopen_folder.setObjectName("actionopen_folder")
        #self.actionopen_folder.setStatusTip('Open folder——打开文件夹！')
        self.actionexit_it = QtWidgets.QAction(MainWindow)
        self.actionexit_it.setObjectName("actionexit_it")
        self.actionexit_it.setStatusTip('Exit it——退出程序！')
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuHelp_me = QtWidgets.QMenu(self.menuHelp)
        self.menuHelp_me.setObjectName("menuHelp_me")
        self.menuAbout_us = QtWidgets.QMenu(self.menuHelp)
        self.menuAbout_us.setObjectName("menuAbout_us")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout_QT = QtWidgets.QAction(MainWindow)
        self.actionAbout_QT.setObjectName("actionAbout_QT")
        self.actionAbout_QT.setStatusTip('About QT designer——关于那个！')
        self.actionAbout_PYQT = QtWidgets.QAction(MainWindow)
        self.actionAbout_PYQT.setObjectName("actionAbout_PYQT")
        self.actionAbout_PYQT.setStatusTip('About PYQT5——关于这个！')
        self.actionAbout_ZJU = QtWidgets.QAction(MainWindow)
        self.actionAbout_ZJU.setObjectName("actionAbout_ZJU")
        self.actionAbout_ZJU.setStatusTip('About Zhejiang University——关于浙江大学！')
        self.actionSelect = QtWidgets.QAction(MainWindow)
        self.actionSelect.setObjectName("actionSelect")
        self.actionSelect.setStatusTip('About ——数据的采集！')
        self.actionAnaly = QtWidgets.QAction(MainWindow)
        self.actionAnaly.setObjectName("actionAnaly")
        self.actionAnaly.setStatusTip('About ——数据的分析！')

        self.menubar.addAction(self.menuFile.menuAction())#把栏目添加到主菜单中
        #self.menuFile.addAction(self.menuFile_open.menuAction())
        self.menuFile.addAction(self.menuFile_exit.menuAction())
        #self.menuFile_open.addAction(self.actionopen_file)
        #self.menuFile_open.addAction(self.actionopen_folder)
        self.menuFile_exit.addAction(self.actionexit_it)
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuHelp.addAction(self.menuHelp_me.menuAction())
        self.menuHelp.addAction(self.menuAbout_us.menuAction())
        self.menuHelp_me.addAction(self.actionSelect)
        self.menuHelp_me.addAction(self.actionAnaly)
        self.menuAbout_us.addAction(self.actionAbout_QT)
        self.menuAbout_us.addAction(self.actionAbout_PYQT)
        self.menuAbout_us.addAction(self.actionAbout_ZJU)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))#为栏目命名
        self.button_Browse.setText(_translate("MainWindow", "选择目录"))
        self.groupBox.setTitle(_translate("MainWindow", "选择数据导入方式"))
        self.folderbutton.setText(_translate("MainWindow", "从文件夹导入数据"))
        self.directlybutton.setText(_translate("MainWindow", "从示波器获取数据"))
        self.selectButton.setText(_translate("MainWindow", "采集/分析"))
        self.stopButton.setText(_translate("MainWindow", "停止采集"))
        self.label_2.setText(_translate("MainWindow", "峰值阈值(V)"))
        self.label_3.setText(_translate("MainWindow", "触发电平(V)"))
        self.label_5.setText(_translate("MainWindow", "μ子峰谷差值"))
        self.label_6.setText(_translate("MainWindow", "电子峰谷差值"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        #self.menuFile_open.setTitle(_translate("MainWindow", "Open file!"))
        self.menuFile_exit.setTitle(_translate("MainWindow", "Exit!"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuHelp_me.setTitle(_translate("MainWindow", "Help me!"))
        self.menuAbout_us.setTitle(_translate("MainWindow", "About us!"))
        #self.actionopen_file.setText(_translate("MainWindow", "Open file"))
        #self.actionopen_folder.setText(_translate("MainWindow", "Open folder"))
        self.actionexit_it.setText(_translate("MainWindow", "Exit it"))
        self.actionAbout_QT.setText(_translate("MainWindow", "About QT"))
        self.actionAbout_PYQT.setText(_translate("MainWindow", "About PYQT"))
        self.actionAbout_ZJU.setText(_translate("MainWindow", "About ZJU"))
        self.actionSelect.setText(_translate("MainWindow", "Select?"))
        self.actionAnaly.setText(_translate("MainWindow", "Analysics?"))

from mplwidget import MplWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mplMainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(mplMainWindow)
    mplMainWindow.show()
    sys.exit(app.exec_())